[workspace]
members = [
    "bindings/nostr-ffi",
    "bindings/nostr-js",
    "bindings/nostr-sdk-ffi",
    "bindings/nostr-sdk-js",
    "crates/nostr",
    "crates/nostr-sdk",
    "crates/nostr-sdk-net",
]
default-members = ["crates/nostr*"]
resolver = "2"

[workspace.package]
homepage = "https://github.com/rust-nostr/nostr"
repository = "https://github.com/rust-nostr/nostr.git"
license = "MIT"
rust-version = "1.64.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
panic = "abort"
